const path = require('path');
const fs = require('fs');

const distDir = path.resolve(__dirname, 'dist');

const port = parseInt(process.env.PORT || '4321', 10);

const server = Bun.serve({
  port,
  hostname: '0.0.0.0',
  fetch(req) {
    const url = new URL(req.url);
    let pathname = decodeURIComponent(url.pathname);
    if (pathname === '/') pathname = '/index.html';

    // Prevent Path Traversal (CWE-22)
    let filePath = path.resolve(distDir, '.' + pathname);
    if (!filePath.startsWith(distDir)) {
      return new Response('Forbidden', { status: 403 });
    }

    // If directory, look for index.html
    if (fs.existsSync(filePath) && fs.statSync(filePath).isDirectory()) {
      filePath = path.join(filePath, 'index.html');
    }

    // Alias /sitemap.xml to /sitemap-index.xml if generated by @astrojs/sitemap
    if (pathname === '/sitemap.xml' && !fs.existsSync(filePath)) {
      const sitemapIndex = path.join(distDir, 'sitemap-index.xml');
      if (fs.existsSync(sitemapIndex)) filePath = sitemapIndex;
    }

    // If file doesn't exist, try with .html
    if (!fs.existsSync(filePath) && fs.existsSync(filePath + '.html')) {
      filePath = filePath + '.html';
    }

    // Security headers for all responses
    const securityHeaders = {
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'SAMEORIGIN',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    };

    // Serve file with optimized Cache-Control headers
    if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
      const ext = path.extname(filePath).toLowerCase();
      const headers = { ...securityHeaders };
      const isImmutableAsset = pathname.includes('/_astro/');

      const mimeMap = {
        '.html': 'text/html; charset=utf-8',
        '.css': 'text/css; charset=utf-8',
        '.js': 'application/javascript; charset=utf-8',
        '.json': 'application/json; charset=utf-8',
        '.svg': 'image/svg+xml',
        '.xml': 'application/xml; charset=utf-8',
        '.txt': 'text/plain; charset=utf-8',
        '.webp': 'image/webp',
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.ico': 'image/x-icon',
        '.woff2': 'font/woff2',
        '.woff': 'font/woff',
        '.ttf': 'font/ttf',
      };

      if (mimeMap[ext]) {
        headers['Content-Type'] = mimeMap[ext];
      }

      if (isImmutableAsset) {
        headers['Cache-Control'] = 'public, max-age=31536000, immutable';
      } else if (ext === '.html') {
        headers['Cache-Control'] = 'public, max-age=0, must-revalidate';
      } else if (ext === '.xml' || ext === '.txt') {
        headers['Cache-Control'] = 'public, max-age=86400';
      }

      const isCompressible = /\.(html|css|js|svg|xml|txt|json)$/.test(ext);
      const acceptEncoding = req.headers.get('accept-encoding') || '';

      if (isCompressible && acceptEncoding.includes('gzip')) {
        headers['Content-Encoding'] = 'gzip';
        headers['Vary'] = 'Accept-Encoding';
        const fileData = fs.readFileSync(filePath);
        return new Response(Bun.gzipSync(fileData), { headers });
      }

      return new Response(Bun.file(filePath), { headers });
    }

    // Serve custom 404 if available
    const notFoundPage = path.join(distDir, '404', 'index.html');
    const notFoundDirect = path.join(distDir, '404.html');
    const custom404 = fs.existsSync(notFoundPage) ? notFoundPage : (fs.existsSync(notFoundDirect) ? notFoundDirect : null);

    if (custom404) {
      return new Response(Bun.file(custom404), {
        status: 404,
        headers: {
          ...securityHeaders,
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'no-cache',
        }
      });
    }

    return new Response('Not Found', {
      status: 404,
      headers: securityHeaders
    });
  }
});

console.log(`Logrus Web Server running at http://localhost:${server.port}`);
